language: node_js
node_js:
- '8'
cache:
  directories:
  - ./server/node_modules
  - ./server/client/node_modules
before_script: 
  - cd ./server && npm install
  - cd ./client && npm install
  - cd ..
script:
- cd client
- npm test
- npm run build 
- cd ..

deploy:
    provider: heroku
    api_key: 658742ce-2954-4b44-be8b-723b024f062a
    app:
      master: daledger-prod
      test: daledger-test
    skip_cleanup: true
    github_token: $GITHUB_TOKEN

notifications:
    email:
        recipients:
            - emerysolutions@yahoo.co.uk
        on_success: always 
        on_failure: always 
